name: package-version-tag

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'main')
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: EndBug/version-check@v2
        id: check
      - if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found. New version is ${{ steps.check.outputs.version }}"'
      - if: steps.check.outputs.changed == 'true'
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git tag ${{ steps.check.outputs.version }}
          git push --tags
